config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :tasks, only: [:show, :edit, :destroy, :update]

    resources :task_lists, except: [:new] do
      resources :tasks, except: [:index, :edit, :show, :destroy, :update]
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'task_lists#new'
  end
# => Produce un loop:
#  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), via: [:get, :post]
  match '', to: redirect("/#{I18n.default_locale}"), via: [:get, :post]
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <button class="navbar-toggler p-0 border-0" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "TODO-Rails", root_url, class: 'navbar-brand' %>
  <div class="navbar-collapse collapse" id="navbarResponsive">

  <ul class="nav navbar-nav">
    <li class="nav-item ">
      <%= link_to t('application.all_my_task_list'), task_lists_url, class: 'nav-link' %>
    </li>

    <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="responsiveNavbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%=t('application.language')%></a>
            <div class="dropdown-menu" aria-labelledby="responsiveNavbarDropdown">
              <div class="dropdown-item">
              <%= image_tag("en.svg", size: "18") %>
              <%= link_to_unless_current "English", url_for(locale: "en") %>
            </div>
            <div class="dropdown-item">
              <%= image_tag("es.svg", size: "18") %>
              <%= link_to_unless_current "Español", url_for(locale: "es") %>
            </div>
        </div>
    </li>

    <li class="nav-item ">
      <a class="nav-link" data-toggle="modal" data-target=".bd-example-modal-sm" href="#"><%=t('application.about')%></a>
    </li>
  </ul>
</div>
</nav>
<br>

<!-- Small modal -->

<div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
              <h4 class= "modal-title"><strong><%= ApplicationHelper::NAME %></strong></h4>
          </div>
      <div class="modal-body">
      <p>© <%= ApplicationHelper::YEAR %> - <%= ApplicationHelper::DEVELOPERS %></p>
      <p><%= ApplicationHelper::NAME %> <a target="_blank" href="https://github.com/kity-linuxero/todorails/blob/master/changelog.md"> v<%= ApplicationHelper::VERSION %></a><br>
      <small><a target="_blank" href="https://raw.githubusercontent.com/kity-linuxero/todorails/master/LICENSE"> MIT License</a></p></small>
      <small><%= t('application.bug1') %> <a target="_blank" href="https://github.com/kity-linuxero/todorails/issues/new"> <%= t('application.bug2')%></small>
      </div>
      <div class="modal-footer">
        UNLP | TTPS 2016 - Ruby <a target="_blank" href="https://github.com/kity-linuxero/todorails">
          <%= image_tag("git.png", size: "20") %>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notice.html.erb
<% unless notice.nil? %>
<small>
<p class="alert alert-info" role="alert" id="notice" style="display:none">
<%= notice %>
</p>
</small>
<script>$('#notice').show(500).delay(2500).hide(800)</script>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang=<%= I18n.locale %>>
  <head>
    <title><%= ApplicationHelper::NAME %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">

    <%= yield %>
    </div>
</body>

</html>